# Generated by Django 3.2.9 on 2022-06-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220606_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='is_applicant',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='usertype',
            name='type',
            field=models.CharField(choices=[('APPLICANT', 'Applicant'), ('RECRUITER', 'Recruiter')], default='APPLICANT', max_length=50),
        ),
    ]
