# Generated by Django 3.2.9 on 2022-07-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='required_experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
