# Generated by Django 3.2.9 on 2022-06-12 17:49

import company.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessStream',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company.company')),
                ('type', models.CharField(choices=[('IT', 'It'), ('PETROLEUM', 'Petroleum'), ('TOURISM', 'Tourism')], default='IT', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='establishment_date',
            field=models.IntegerField(blank=True, null=True, validators=[company.models.validate_interval]),
        ),
    ]
